### ISSUE TITLE
Issue with Purple Wisteria Leaves?

### ISSUE THREAD

**Issue by robertfwallis** [team-abnormals/environmental#128]
`java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{environmental:purple_wisteria_leaves}`

I had two crash logs and both contain this line in particular that stands out to me. Happens mid-game when flying around in creative. Latest crash log attached.

[crash-2021-03-01_11.37.53-server.txt](https://github.com/team-abnormals/environmental/files/6061292/crash-2021-03-01_11.37.53-server.txt)

**Comment by JuicyCosmos** [comment]
Can confirm. Mine says problem is with White Wisteria Leaves. We both have rapid leaves decay and it seems not compatible?

**Comment by JuicyCosmos** [comment]
So on the rapid leaves decay mod's issue page there's report it also crashes with the Abyss' trees. There the mod author uploaded a new version which solves that problem. I wonder if it'll solve the conflict with Environmental as well. I can't test it myself since I'm using 1.16.4 and the new rapid leaves decay is for 1.16.5. For me I switched to fast leaves decay and the world's working fine again.
