### ISSUE TITLE
MOD no working IN SERVER

### ISSUE THREAD

**Issue by MrJorman** [team-abnormals/environmental#329]
MOD no working IN SERVER, test more forge version. Enviromental mod no startup in server.

**Comment by MrJorman** [comment]
CLIENT also no working 
![image](https://user-images.githubusercontent.com/55187962/223160146-756a7deb-e56e-4e02-9f78-c9c679090c30.png)

**Comment by MrJorman** [comment]
please fix. Enviromental mod no working :C

**Comment by MrJorman** [comment]
I put versions with CurseForge - the client started, but the server does not want to work in any way.

**Comment by MrJorman** [comment]
Fix please startup mod from server.

**Comment by MrJorman** [comment]
fckng admins, bagel you retard school boy

**Comment by MrJorman** [comment]
doesn't fix mods' mistakes, doesn't give a damn about his subscribers, blocks them everywhere, a finished girl

**Comment by MrJorman** [comment]
please fix..

**Comment by MrJorman** [comment]
Mod no working in Server, Forge .

**Comment by MrJorman** [comment]
![dmitriy-mina-mina](https://user-images.githubusercontent.com/55187962/224335934-b51c8235-cd07-4b8c-be7a-e0e7389c0d85.gif)
Admins

**Comment by dabomb6405** [comment]
be patient bruh

also if you want the bug fixed you should provide a full crashlog, not just a screenshot

**Comment by MrJorman** [comment]
> be patient bruh
> 
> also if you want the bug fixed you should provide a full crashlog, not just a screenshot

no crash-logs. server no startup.

**Comment by MrJorman** [comment]
No working in latest update also.

**Comment by Yvannas** [comment]
Hi there, I have a server setup on a Dell workstation and I am running this fine with about 50 other mods. I am running the same mod pack on my laptop and that is working fine too. 
Unfortunately, my friend who plays on my server with me, has been unable to load Minecraft ever since we added the Environmental mod. 
After a considerable amount of testing we have found that: 
- the first java screen pops up and then hangs - we do not get to the red mojang screen
- loading vs not loading is extremely inconsistent 
- it always loads when Environmental is the only mod in there
- when loaded with (for eg) mystical Agriculture it will sometimes load ... and sometimes not
- the more mods included the more likely it will hang 
- the two client computers are fairly similarly specced (her computer is better than my laptop :-) although I do have more ram) 
- the only really significant difference is that both of the working computers are intel based and hers is AMD 
- the intermittent nature of the issue is making it hard to get a meaningful log 
- we have tried different java types, different loader ... and the same things happen

I can get error logs but as I said, these are not being terribly useful for us anyway ... the only consistent thing... is her computer and this mod :-(

**Comment by Yvannas** [comment]
@MrJorman - are the computers you are using for client and server amd or Intell?
@dabomb6405 - unfortunately the other chap is right - there is no crash, Java hangs and wont get to the Mojang screen so doesnt actually crash 
Please let me know if there is info you need from my friend and I that would help to understand what is going on

**Comment by MrJorman** [comment]
Intel. I use 2 mods: Blueprint and Enviromental. Java 17.

**Comment by bageldotjpg** [comment]
Since this is all one issue going to redirect this to #362
