### ISSUE TITLE
Cattails are able to grow seed on mud, even if they are not waterlogged

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#337]
This is inconsistent with the behavior of other stages of cattail, which are unable to grow without being waterlogged.

**Comment by bageldotjpg** [comment]
Correct.
Mud is tied to the seeds.
Water is tied to the physical size.

**Comment by thelegitdolt** [comment]
most intuitive abnormals mechanic

**Comment by bageldotjpg** [comment]
Your snark is misplaced, because your suggested solution is less intuitive. Having seeds not be biconditional allows more control over the crop.
Rather than having seeds be tied to water AND mud, seeds are just tied to mud. This allows seeded cattails to be grown outside of water, for decorative purposes, and includes less conditions, thus being more intuitive.
